[package]
name = "wchat-robot-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inline-python = "0.7.1"

[dependencies.pyo3]
version = "0.14.5"
features = ["auto-initialize"]
